name: Generate Javadocs

on:
  release:
    types:
    - created
  workflow_dispatch:

jobs:
  genDocs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Generate Javadocs
      run: ./gradlew javadoc
    - name: Push Javadocs
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
